---
name: codeworld-demo
version: 0.1.0.0
github: "patritzenfeld/codeworld-demo"
license: BSD-3-Clause
author: "Patrick Ritzenfeld"
maintainer: "patrick.ritzenfeld@uni-due.de"
copyright: "2025 Patrick Ritzenfeld"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - static/*

description: Please see the README on GitHub at <https://github.com/patritzenfeld/codeworld-demo#readme>

dependencies:
  - base >= 4.7 && < 5
  - effectful-core
  - extra
  - directory
  - filepath
  - haskell-template-task
  - haskell-template-task-raw
  - wl-pprint-text
  - hyperbole
  - atomic-css
  - mtl
  - wai-middleware-static
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror
  - -Widentities
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  codeworld-demo-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - codeworld-demo
      - codeworld-tasks
      - IOTasks

tests:
  codeworld-demo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - codeworld-demo
