---
resolver: nightly-2025-10-07

packages:
  - .

extra-deps:
  - QuickCheck-2.15.0.1
  - hyperbole-0.7.1
  - atomic-css-0.2.0
  - git: https://github.com/fmidue/codeworld-tasks
    commit: 67bc363e81485a14a1aa624b8dd1d47a067d7bf0
  - git: https://github.com/fmidue/haskell-template-task
    commit: 4c5dc589589ec1647878f0f1daa6101159470c18
    subdirs:
      - .
      - raw

flags:
  haskell-template-task-raw:
    iotasks: false

ghc-options:
  codeworld-tasks: -Wno-deriving-typeable
