---
resolver: nightly-2025-07-23

packages:
  - .

extra-deps:
  - hyperbole-0.5.0
  - atomic-css-0.2.0
  - git: https://github.com/fmidue/IOTasks
    commit: 659385853299b4fcb27bd26e7ab185af27a9d00a
  - git: https://github.com/IagoAbal/haskell-z3
    commit: b77a17e5eeb7db82656bcbcd66c6e952207e69ca
  - git: https://github.com/owestphal/type-match
    commit: e1afab43d2e8bfa5e2006492ed34060036e7be51
  - git: https://github.com/fmidue/haskell-template-task
    commit: 81278a30d63449879c39f403a2cad108ab0785ec
    subdirs:
      - .
      - raw
