---
resolver: nightly-2025-10-07

packages:
  - .

extra-deps:
  - QuickCheck-2.15.0.1
  - hyperbole-0.5.0
  - atomic-css-0.2.0
  - git: https://github.com/fmidue/codeworld-tasks
    commit: 67bc363e81485a14a1aa624b8dd1d47a067d7bf0
  - git: https://github.com/fmidue/haskell-template-task
    commit: 6c2956b1a34ea5bffc78f13cdaf5294a9d435fbd
    subdirs:
      - .
      - raw

flags:
  haskell-template-task-raw:
    iotasks: false

ghc-options:
  codeworld-tasks: -Wno-deriving-typeable
