---
resolver: nightly-2025-10-07

packages:
  - .

extra-deps:
  - QuickCheck-2.15.0.1
  - hyperbole-0.7.1
  - atomic-css-0.2.0
  - git: https://github.com/fmidue/codeworld-tasks
    commit: 67bc363e81485a14a1aa624b8dd1d47a067d7bf0
  - git: https://github.com/fmidue/haskell-template-task
    commit: d2f18e228d90f5828aa55d6649448c7eda12c2b7
    subdirs:
      - .
      - raw

flags:
  haskell-template-task-raw:
    iotasks: false

ghc-options:
  codeworld-tasks: -Wno-deriving-typeable
