---
name: Haskell Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: 'Set up HLint'
        uses: haskell-actions/hlint-setup@v2
        with:
          version: '3.8'

      - name: 'Run HLint'
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["src/"]'
          fail-on: suggestion
