---
name: Xrefcheck

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  xrefcheck:
    name: Check references
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Run Link Checker
        uses: serokell/xrefcheck-action@81d3967156933307f52fc52f8dc7fa5e947509c2 # v1
        with:
          xrefcheck-args: --ignore ./README.md
